// ここに あたらしい ゲームを ついかしていくよ！
// 1. games フォルダの なかに あたらしい フォルダを つくる（例: games/atarashii-game）
// 2. そのなかに index.html を つくる（トップページに もどる リンクを わすれずに）
// 3. したの リストに 1こう ついかする

const GAMES = [
  {
    id: 'mario',
    title: 'スーパーそうすけラン',
    emoji: '🧒',
    color: '#4C7BF3',
    path: 'games/mario/index.html',
    desc: 'すすんで、とんで、てきを よけよう！',
  },
  {
    id: 'zombie',
    title: 'そうすけの ゾンビたいじ',
    emoji: '🧟',
    color: '#5DBB63',
    path: 'games/zombie/index.html',
    desc: '5つの ぶきで ゾンビから いえを まもろう！',
  },
  {
    id: 'stage-quest',
    title: 'そうすけの ステージクエスト',
    emoji: '🗺️',
    color: '#F5A623',
    path: 'games/stage-quest/index.html',
    desc: '3つの ステージを クリアしよう！パズルが いっぱい あるよ。',
  },
  {
    id: 'tictactoe',
    title: 'そうすけの ○×ゲーム',
    emoji: '⭕',
    color: '#6FCF97',
    path: 'games/tictactoe/index.html',
    desc: 'コンピューターと まるばつゲームで しょうぶしよう！',
  },
  {
    id: 'janken',
    title: 'そうすけの じゃんけんゲーム',
    emoji: '✂️',
    color: '#FF6B6B',
    path: 'games/janken/index.html',
    desc: 'コンピューターと じゃんけん しょうぶ！',
  },
  {
    id: 'marble-cup',
    title: 'そうすけの くるくるビーだま',
    emoji: '🥤',
    color: '#7EC8E3',
    path: 'games/marble-cup/index.html',
    desc: 'かみコップの ビーだまを まわしつづけよう！タイムアタック！',
  },
  {
    id: 'tidy-room',
    title: 'そうすけの おかたづけゲーム',
    emoji: '🧹',
    color: '#FFC1E3',
    path: 'games/tidy-room/index.html',
    desc: '30びょういないに 13この ものを かたづけよう！',
  },
  {
    id: 'toilet-rush',
    title: 'そうすけの トイレまでダッシュ',
    emoji: '🚻',
    color: '#6EE7F9',
    path: 'games/toilet-rush/index.html',
    desc: 'めいろを すすんで、じかんないに トイレに いこう！',
  },
  {
    id: 'bowling',
    title: 'そうすけの ボウリング',
    emoji: '🎳',
    color: '#FF9A9E',
    path: 'games/bowling/index.html',
    desc: 'ねらいと ちからを きめて、10ぽん ぜんぶ たおそう！',
  },
  {
    id: 'katanuki',
    title: 'そうすけの かたぬき',
    emoji: '🍬',
    color: '#FD6E6A',
    path: 'games/katanuki/index.html',
    desc: 'せんの まわりを なぞって、われないように けずろう！',
  },
  {
    id: 'heist',
    title: 'そうすけの おたからどろぼう',
    emoji: '🥷',
    color: '#4A6572',
    path: 'games/heist/index.html',
    desc: 'けいびに みつからずに おかねを あつめて、おみせで うろう！10ステージ！',
  },
  {
    id: 'coloring',
    title: 'そうすけの ぬりえ',
    emoji: '🎨',
    color: '#FF9A56',
    path: 'games/coloring/index.html',
    desc: 'すきな たべものを えらんで、すきな いろで ぬろう！',
  },
  {
    id: 'chameleon',
    title: 'そうすけの めっちゃカメレオン',
    emoji: '🦎',
    color: '#4CAF50',
    path: 'games/chameleon/index.html',
    desc: 'かべと おなじ いろに へんしんして、さがしやさんから かくれよう！',
  },
  {
    id: 'car-fix',
    title: 'そうすけの くるまピカピカ',
    emoji: '🚗',
    color: '#FF6B6B',
    path: 'games/car-fix/index.html',
    desc: 'タイヤを つけて、よごれを ふいて、まどと ドアを なおそう！',
  },
  {
    id: 'my-phone',
    title: 'そうすけの マイケータイ',
    emoji: '📱',
    color: '#7DE07D',
    path: 'games/my-phone/index.html',
    desc: 'じぶんの ケータイで、でんたくや おんがくなど 20この アプリで あそぼう！',
  },
  {
    id: 'hero-battle',
    title: 'そうすけの ヒーローたいけつ',
    emoji: '🦸',
    color: '#4C7BF3',
    path: 'games/hero-battle/index.html',
    desc: 'すきな ヒーローと たたかう あいてを えらんで、たいけつ しよう！',
  },
  {
    id: 'restaurant',
    title: 'そうすけの レストランタイミング',
    emoji: '🍽️',
    color: '#FF9A56',
    path: 'games/restaurant/index.html',
    desc: 'ちゅうもんを うけて、りょうりを つくって サーブしよう！さいごは あらって かんりょう。',
  },
  {
    id: 'who-is-this',
    title: 'そうすけの だれかな？',
    emoji: '🕵️',
    color: '#9B59B6',
    path: 'games/who-is-this/index.html',
    desc: '3にんの キャラクターを おぼえて、なまえを パスワードで こたえよう！',
  },
  {
    id: 'whack-a-mole',
    title: 'そうすけの もぐらたたき',
    emoji: '🐹',
    color: '#6AB85E',
    path: 'games/whack-a-mole/index.html',
    desc: 'あなから でてきた もぐらを、はやく タップして たたこう！',
  },
  {
    id: 'sansuu',
    title: 'そうすけの たしざん ひきざん',
    emoji: '➕',
    color: '#4C7BF3',
    path: 'games/sansuu/index.html',
    desc: 'もんだいの こたえを 4つの なかから えらんで、なんもん とけるか ちょうせん！',
  },
  {
    id: 'keyboard-paint',
    title: 'そうすけの キーボードぬりぬり',
    emoji: '⌨️',
    color: '#7EC8E3',
    path: 'games/keyboard-paint/index.html',
    desc: 'キーボードの キーを すきな いろで ぬろう！🧑のキーを おすと 人が とびだすよ！',
  },
  {
    id: 'squishy',
    title: 'そうすけの スクイーズ ぎゅっ',
    emoji: '🧈',
    color: '#FFC1E3',
    path: 'games/squishy/index.html',
    desc: 'バターや パンケーキ、ラップの スクイーズを ゆびで ぎゅっと おしてみよう！',
  },
  {
    id: 'fruit-merge',
    title: 'そうすけの フルーツマージ',
    emoji: '🍎',
    color: '#6FCF97',
    path: 'games/fruit-merge/index.html',
    desc: 'おなじ フルーツを ぶつけて、どんどん おおきい フルーツに マージしよう！',
  },
  {
    id: 'friend-collect',
    title: 'そうすけの おともだちあつめ',
    emoji: '🚕',
    color: '#7EC8E3',
    path: 'games/friend-collect/index.html',
    desc: '20びょう いないに こうえんの おともだち10にんを あつめて、タクシーに のろう！',
  },
  {
    id: 'pizza-delivery',
    title: 'そうすけの ピザとどけ',
    emoji: '🍕',
    color: '#FFC1E3',
    path: 'games/pizza-delivery/index.html',
    desc: 'バイクで レーンを かえながら、じゃまものを よけて 50メートル ピザを とどけよう！',
  },
  {
    id: 'body-maze',
    title: 'そうすけの からだの なか たんけん',
    emoji: '🫀',
    color: '#FF9E9E',
    path: 'games/body-maze/index.html',
    desc: 'くちから はいって、からだの なかの めいろを すすんで、そとまで でられるかな？',
  },
  {
    id: 'boxing',
    title: 'そうすけの ボクシング',
    emoji: '🥊',
    color: '#FF9A9E',
    path: 'games/boxing/index.html',
    desc: 'Fパンチと Gキックで あいてを こうげき！ ゲージが たまったら Pで めちゃくちゃパンチ！',
  },
  {
    id: 'favorite-quiz',
    title: 'そうすけの なにが すき？',
    emoji: '💭',
    color: '#FFC1E3',
    path: 'games/favorite-quiz/index.html',
    desc: 'くだもの、どうぶつ、やさいなど、5つの なかまから すきな ものを えらんでいこう！',
  },
  {
    id: 'hide-and-seek',
    title: 'そうすけの かくれんぼ',
    emoji: '🙈',
    color: '#FFC1E3',
    path: 'games/hide-and-seek/index.html',
    desc: 'クローゼットや テーブルの したなど、いえの なかの かくれる ばしょを さがして オニから かくれよう！',
  },
  {
    id: 'movie-theater',
    title: 'そうすけの えいがかん',
    emoji: '🎬',
    color: '#6B4E9E',
    path: 'games/movie-theater/index.html?v=2',
    desc: 'オリジナルヒーローの えいがを えらんで、えいがかんで みてみよう！',
  },
  {
    id: 'hide-homework',
    title: 'そうすけの べんきょう かくし',
    emoji: '📄',
    color: '#FF9A9E',
    path: 'games/hide-homework/index.html',
    desc: 'フライパンで もやしたり、トイレに ながしたり…プリントを どうやって かくす？',
  },
  {
    id: 'find-phone',
    title: 'そうすけの けいたい どこ？',
    emoji: '📱',
    color: '#FFE0B2',
    path: 'games/find-phone/index.html',
    desc: 'キッチンの うえや プリントの したなど、おうちの なかから けいたいを さがしだそう！',
  },
  {
    id: 'outfit-picker',
    title: 'そうすけの きがえっこ',
    emoji: '👕',
    color: '#7EC8E3',
    path: 'games/outfit-picker/index.html',
    desc: 'どの Tシャツと どの ズボンが きたい？ すきな ふくを えらんで きせかえよう！',
  },
  {
    id: 'spider-patrol',
    title: 'そうすけの くもたいじ',
    emoji: '🕷️',
    color: '#C8F7C5',
    path: 'games/spider-patrol/index.html',
    desc: 'かべに でてきた くもを、そとに にがすか たいじするか えらぼう！',
  },
  {
    id: 'dot-muncher',
    title: 'そうすけの まるまるダッシュ',
    emoji: '🟡',
    color: '#4C7BF3',
    path: 'games/dot-muncher/index.html',
    desc: 'めいろの まるを ぜんぶ たべつくそう！おおきい まるで おばけを ぎゃくしゅうできるよ！',
  },
  {
    id: 'town-walk',
    title: 'そうすけの まちあるき',
    emoji: '🚶',
    color: '#7EC8E3',
    path: 'games/town-walk/index.html?v=2',
    desc: 'ピザやさんや ホテルなど、5つの まちの たてものに はいって いろんな たいけんを しよう！',
  },
  {
    id: 'conbini-baito',
    title: 'そうすけの コンビニバイト',
    emoji: '🏪',
    color: '#7EC8E3',
    path: 'games/conbini-baito/index.html?v=5',
    desc: 'おきゃくさんが しなものを かって レジに くるよ。ふつうの ひとには レジ、わるものには でんわ！しなものの ほじゅうも あるよ。',
  },
  {
    id: 'tooth-brush',
    title: 'そうすけの はみがき たいけつ',
    emoji: '🪥',
    color: '#7EC8E3',
    path: 'games/tooth-brush/index.html?v=2',
    desc: 'よごれた はを タップして みがいて、みんなの はを ピカピカに してあげよう！',
  },
  {
    id: 'eating-asmr',
    title: 'そうすけの もぐもぐ ASMR',
    emoji: '😋',
    color: '#FF9A9E',
    path: 'games/eating-asmr/index.html',
    desc: 'すきな たべものを えらんで、タップして もぐもぐ。クチャッと たべる おとが きもちいいよ！',
  },
  {
    id: 'keycap-clean',
    title: 'そうすけの キーキャップ そうじ',
    emoji: '🧽',
    color: '#7EC8E3',
    path: 'games/keycap-clean/index.html',
    desc: 'よごれた キーは スポンジで シャシャシャッ、ぐねぐねの キーは つまようじで ポンッと きれいに しよう！',
  },
  {
    id: 'grandma-escape',
    title: 'そうすけの おばあちゃんちだっしゅつ',
    emoji: '🔑',
    color: '#C8A97E',
    path: 'games/grandma-escape/index.html?v=3',
    desc: 'はこや れいぞうこなど おばあちゃんちの なかを さがして 🔑かぎを みつけ、げんかんから にげよう！',
  },
  {
    id: 'would-you-rather',
    title: 'そうすけの あなたは どっち？',
    emoji: '🍫',
    color: '#FFC1E3',
    path: 'games/would-you-rather/index.html?v=3',
    desc: 'やじるしで たべものに ちかづいて あじみ、「どちらが いい？」に こたえよう！ぜんぶで 10ステージ！',
  },
  {
    id: 'app-maker',
    title: 'そうすけの アプリづくり',
    emoji: '📱',
    color: '#7EC8E3',
    path: 'games/app-maker/index.html?v=4',
    desc: 'ボタンや テキスト、グラフなど いろんな どうぐを つかって、じぶんだけの アプリを つくろう！',
  },
  {
    id: 'brazil-explore',
    title: 'そうすけの ブラジルたんけん',
    emoji: '🇧🇷',
    color: '#4CAF50',
    path: 'games/brazil-explore/index.html',
    desc: 'やじるしで あるいて、ブラジルの おみせを 6つ たんけんしよう！パン・デ・ケイジョや アサイーも あるよ！',
  },
  {
    id: 'timer-stop',
    title: 'そうすけの 10びょう ストップ',
    emoji: '⏱️',
    color: '#FFD966',
    path: 'games/timer-stop/index.html?v=2',
    desc: 'タイマーが みえなくなっても、あたまの なかで かぞえて ちょうど 10びょうで ストップしよう！',
  },
  {
    id: 'country-quiz',
    title: 'そうすけの どこの くに クイズ',
    emoji: '🌍',
    color: '#AEE1FF',
    path: 'games/country-quiz/index.html',
    desc: 'こっきを みて、どこの くにか あてよう！かんたん→ノーマル→ハードと むずかしく なるよ。',
  },
];
